# Generated by Django 5.2.6 on 2025-09-09 19:07

import app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=2, verbose_name='Nom de famille')),
                ('birth_date', models.DateField(validators=[app.models.validate_not_future], verbose_name='Date de naissance')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationnalité')),
            ],
            options={
                'verbose_name': 'auteur',
                'verbose_name_plural': 'auteurs',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50, verbose_name='Titre du livre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prix du livre')),
                ('summary', models.CharField(blank=True, max_length=50, verbose_name='Résumé du livre')),
                ('date', models.DateField(validators=[app.models.validate_not_future], verbose_name='Date de publication')),
                ('edition', models.CharField(verbose_name='Edition du livre')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.author', verbose_name='Auteurs')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ('code', 'title'),
            },
        ),
    ]
