# Generated by Django 5.2.6 on 2025-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_author_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Code du livre'),
        ),
    ]
