# Generated by Django 5.2.6 on 2025-10-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nationality_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nationnalité'),
        ),
        migrations.AddField(
            model_name='author',
            name='nationality_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Nationnalité'),
        ),
        migrations.AddField(
            model_name='book',
            name='summary_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Résumé du livre'),
        ),
        migrations.AddField(
            model_name='book',
            name='summary_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Résumé du livre'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Titre du livre'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Titre du livre'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nom'),
        ),
    ]
