# Generated by Django 5.2.7 on 2025-10-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_author_nationality_en_author_nationality_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition_en',
            field=models.CharField(null=True, verbose_name='Edition du livre'),
        ),
        migrations.AddField(
            model_name='book',
            name='edition_fr',
            field=models.CharField(null=True, verbose_name='Edition du livre'),
        ),
    ]
